// packages/angular-library/src/app/form-page/name-form/name-form.component.ts
import { ChangeDetectionStrategy, Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-name-form',
  templateUrl: './name-form.component.html',
})
export class NameFormComponent implements OnInit {

  
  constructor() {
  }
  
  @Input()
  control: any = { value: '' }

  @Input()
  onChange: (val) => void


  ngOnInit(): void {
  }


  handleInputChange(event) {
    const onChange = this.onChange

    if (typeof onChange === 'function') {

      onChange(event.target.value)
    }
  }

}

<div class="p-n" style="border: 1px orange solid;">
  <label>name:</label>
  <input name="name" [value]="control.value" (change)="handleInputChange($event)" />
  <div>value: {{control.value}}</div>
</div>

// packages/vue-library/src/controls/NameForm.vue
<template>
  <div class="p-n" style="border: 1px orange solid">
    <label>name:</label>
    <input name="name" :value="value" @change="handleInputChange($event)" />
    <div>value: {{ value }}</div>
  </div>
</template>

<script>
export default {
  props: {
    control: {
      type: Object,
    },
  },
  computed: {
    value() {
      return this.control?.value;
    },
  },
  methods: {
    handleInputChange(event) {
      this.$emit('change', event.target.value);
    },
  },
};
</script>
